package com.example.pet3

enum class States {
    HEARTBEAT,
    LAMPS_FINDING,
    DOWNLOADING_PROGRAM,
    DOWNLOADING_TIME,
    DOWNLOADING_WIFI_AUTH,
    DOWNLOADING_LAN_SETTING,
    DOWNLOADING_MQTT_AUTH,
    UPLOADING_PROGRAM,
    UPLOADING_TIME,
    UPLOADING_WIFI_AUTH,
    UPLOADING_LAN_SETTING,
    UPLOADING_MQTT_AUTH

}